---
name: build application with variables
on:
    workflow_dispatch:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
env:
    PYTHON_VERSION: '3.9'
jobs:
    jobs1:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v6
            - name: setup python ${{ env.PYTHON_VERSION }} on runner
              uses: actions/setup-python@v6
              with:
                python-version: ${{ env.PYTHON_VERSION }}
    jobs2:
        runs-on: ubuntu-latest
        env:
            job_python_version: '3.10'
        steps:
            - name: checkout code
              uses: actions/checkout@v6
            - name: setup python ${{ env.job_python_version }} on runner
              uses: actions/setup-python@v6
              with:
                python-version: ${{ env.job_python_version }}
    jobs3:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v6
            - name: setup python on runner
              env:
                mystep_PYTHON_VERSION: '3.11'
              uses: actions/setup-python@v6
              with:
                python-version: ${{ env.mystep_PYTHON_VERSION }}
            - name: print a message
              env:
                APPLICATION: PYTHON
              run: echo "THE APPLICATION INSTALLED IS $APPLICATION"
